= `xtr.strings`

== `appendIfMissing(str: String, suffix: String): String`
Returns `str`, appended with `suffix` if it does not already end with `suffix`.

.Example
----
xtr.strings.appendIfMissing('Hello', ' World')
----
.Result
----
'Hello World'
----

== `camelize(str: String): String`
Returns the camelized version of `str`, by removing all spaces and underscores, and capitalizing the first letter of every word after the first.

.Example
----
xtr.strings.camelize('Hello to_everyone')
----
.Result
----
'helloToEveryone'
----

== `capitalize(str: String): String`
Returns the capitalized version of `str`, by capitalizing the first letter of every word.

.Example
----
xtr.strings.capitalize('hello world')
----
.Result
----
'Hello World'
----

== `charCode(char: String): String`
Returns the character-code for the given `char`.

.Example
----
xtr.strings.charCode('*')
----
.Result
----
42
----

== `charCodeAt(str: String, index: Number): String`
Returns the character-code for the character at the given `index` in `str`.

.Example
----
xtr.strings.charCodeAt('_*_', 1)
----
.Result
----
42
----

== `dasherize(str: String): String`
Returns the dasherized version of `str`, by changing alphabetic characters to lowercase, and replacing all spaces and underscores for dashes.

.Example
----
xtr.strings.dasherize('Hello World_X')
----
.Result
----
'hello-world-x'
----

== `ofCharCode(code: Number): String`
Returns the character for the given character-code.

.Example
----
xtr.strings.ofCharCode(42)
----
.Result
----
'*'
----

== `isAlpha(str: String): String`
Returns `true` if the given `str` contains only alphabetic characters, otherwise `false`.

.Example
----
xtr.strings.isAlpha('abcde')
----
.Result
----
true
----

== `isAlphanumeric(str: String): String`
Returns `true` if the given `str` contains only alphanumeric characters, otherwise `false`.

.Example
----
xtr.strings.isAlphanumeric('a1b2cd3e4')
----
.Result
----
true
----

== `isLowerCase(str: String): String`
Returns `true` if the alphabetic characters in the given `str` are all lowercase, otherwise `false`.

.Example
----
xtr.strings.isLowerCase('hello')
----
.Result
----
true
----

== `isNumeric(str: String): String`
Returns `true` if the given `str` contains only numeric characters.

.Example
----
xtr.strings.isNumeric('34634')
----
.Result
----
true
----

== `isUpperCase(str: String): String`
Returns `true` if the alphabetic characters in the given `str` are all uppercse, otherwise `false`.

.Example
----
xtr.strings.isUpperCase('HELLO')
----
.Result
----
true
----

== `isWhitespace(str: String): String`
Returns `true` if the given `str` contains only whitespaces.

.Example
----
xtr.strings.isWhitespace('      ')
----
.Result
----
true
----

== `leftPad(str: String, size: Number, char: String): String`
Returns `str` prepended with enough repetitions of `char` required to meet the given `size`, otherwise returns `str` if its size is already equal or longer than `size`.

.Example
----
xtr.strings.leftPad('Hello', 10, ' ')
----
.Result
----
'     Hello'
----

// todo: num in result?
== `ordinalOf(num: Number): String`
Returns the ordinal name for the given `num`.

.Example
----
xtr.strings.ordinalOf(1)
----
.Result
----
'1st'
----

// todo: document algo
== `pluralize(word: String): String`
Returns the plural of the given `word`.

.Example
----
xtr.strings.pluralize('car')
----
.Result
----
'cars'
----

== `prependIfMissing(str: String, prefix: String): String`
Returns `str`, prepended with `suffix` if it does not already start with `prefix`.

.Example
----
xtr.strings.prependIfMissing('World', 'Hello ')
----
.Result
----
'Hello World'
----

== `repeat(str: String, n: Number): String`
Returns a new `String` with `str` repeated `n` times.

.Example
----
xtr.strings.repeat('hey ', 2)
----
.Result
----
'hey hey hey '
----

== `rightPad(str: String, size: Number, char: String): String`
Returns `str` prepended with enough repetitions of `char` required to meet the given `size`, otherwise returns `str` if its size is already equal or longer than `size`.

.Example
----
xtr.strings.rightPad('Hello', 10, ' ')
----
.Result
----
'Hello     '
----

// todo: document algo
== `singularize(word: String): String`
Returns the singular of the given `word`.

.Example
----
xtr.strings.singularize('cars')
----
.Result
----
'car'
----

== `substringAfter(str1: String, str2: String): String`
Returns the contents of `str1` after the first occurrence of `str2`, otherwise returns `str1` if it does not contain `str2`.

.Example
----
xtr.strings.substringAfter('!XHelloXWorldXAfter', 'X')
----
.Result
----
'HelloXWorldXAfter'
----

== `substringAfterLast(str1: String, str2: String): String`
Returns the contents of `str1` after the last occurrence of `str2`, otherwise returns `str1` if it does not contain `str2`.

.Example
----
xtr.strings.substringAfterLast('!XHelloXWorldXAfter', 'X')
----
.Result
----
'After'
----

== `substringBefore(str1: String, str2: String): String`
Returns the contents of `str1` before the first occurrence of `str2`, otherwise returns `str1` if it does not contain `str2`.

.Example
----
xtr.strings.substringBefore('!XHelloXWorldXAfter', 'X')
----
.Result
----
'!'
----

== `substringBeforeLast(str1: String, str2: String): String`
Returns the contents of `str1` before the last occurrence of `str2`, otherwise returns `str1` if it does not contain `str2`.

.Example
----
xtr.strings.substringBeforeLast('!XHelloXWorldXAfter', 'X')
----
.Result
----
'!XHelloXWorld'
----

== `underscore(str: String): String`
Returns the underscored version (aka snake case) of the given `str`, by changing alphabetic characters to lowercase, and replacing all spaces for underscores.

.Example
----
xtr.strings.underscore('Hello WorldX')
----
.Result
----
'hello_world_x'
----

== `unwrap(str: String, wrap: String): String`
Returns `str` without the given `wrap` as prefix and suffix, if found.

.Example
----
xtr.strings.unwrap('_Hello, world!_', '_')
----
.Result
----
'Hello, world!'
----

== `truncate(str: String, size: Number): String`
Returns `str` truncated by the given `size`.

.Example
----
xtr.strings.truncate('Hello, world!', 5)
----
.Result
----
'Hello'
----

== `wrap(str: String, wrap: String): String`
Returns `str`, prepended and appended with `wrap`.

.Example
----
xtr.strings.wrap('_Hello, world!', '_')
----
.Result
----
'__Hello, world!_'
----

== `wrapIfMissing(str: String, wrap: String): String`
Returns `str`, prepended and appended with `wrap`, if not found.

.Example
----
xtr.strings.wrapIfMissing('_Hello, world!', '_')
----
.Result
----
'_Hello, world!_'
----
