= `xtr.numbers`

== `fromBinary(binary: String | Number): Number`
Returns the `Number` representation for the given `binary`.

.Example
----
xtr.numbers.fromBinary(1100100)
----
.Result
----
100
----

== `fromHex(hexadecimal: String): Number`
Returns the `Number` representation for the given `hexadecimal`.

.Example
----
xtr.numbers.fromHex('F')
----
.Result
----
15
----

== `fromOctal(octal: String | Number): Number`
Returns the `Number` representation for the given `octal`.

.Example
----
xtr.numbers.fromOctal(107136)
----
.Result
----
36446
----

== `fromRadix(value: String | Number, n: Number): Number`
Returns the `Number` representation for the given Base-`n` `value`

.Example
----
xtr.numbers.fromRadixNumber('10', 3)
----
.Result
----
3
----

== `toBinary(number: Number): String`
Returns the binary representation for the given `number`.

.Example
----
xtr.numbers.toBinary(100)
----
.Result
----
'1100100'
----

== `toHex(number: Number): String`
Returns the hexadecimal representation for the given `number`.

.Example
----
xtr.numbers.toHex(15)
----
.Result
----
'F'
----

== `toOctal(number: Number): String`
Returns the octal representation for the given `number`.

.Example
----
xtr.numbers.toOctal(36446)
----
.Result
----
'107136'
----

== `toRadix(value: Number, n: Number): String`
Returns the Base-`n` representation for the given `value` as a `String`.

.Example
----
xtr.numbers.toRadix('3', 3)
----
.Result
----
'10'
----
