= `tro.datetime`

The datetime module is based on the ISO-8601 extended offset date-time format, and the ISO-8601 duration format. The ISO-8601 format is the recommendation of the IETF through RFC 3339: _Date and Time on the Internet_.

Users that need to operate on other date and time formats can use the `parse` function to convert it to the supported format, operate on the result, and optionally output it to any other format with the `format` function.


== `atBeginningOfDay(datetime: String): String`
Returns the given `datetime` at midnight.

.Example
----
tro.datetime.atBeginningOfDay('2020-12-31T23:19:35Z')
----
.Result
----
'2020-12-31T00:00:00Z'
----

== `atBeginningOfHour(datetime: String): String`
Returns the given `datetime` with the minutes and seconds set to zero.

.Example
----
tro.datetime.atBeginningOfHour('2020-12-31T23:19:35Z')
----
.Result
----
'2020-12-31T23:00:00Z'
----

== `atBeginningOfMonth(datetime: String): String`
Returns the given `datetime` with the day set to first of the month, and the time set to midnight.

.Example
----
tro.datetime.atBeginningOfMonth('2020-12-31T23:19:35Z')
----
.Result
----
'2020-12-01T00:00:00Z'
----

== `atBeginningOfWeek(datetime: String): String`
Returns the given `datetime` with the day set to first of the current week, and the time set to midnight.

.Example
----
tro.datetime.atBeginningOfWeek('2020-12-31T23:19:35Z')
----
.Result
----
'2020-12-27T00:00:00Z'
----

== `atBeginningOfYear(datetime: String): String`
Returns the given `datetime` with the day/month set to January 1st, and the time set to midnight.

.Example
----
tro.datetime.atBeginningOfYear('2020-12-31T23:19:35Z')
----
.Result
----
'2020-01-01T00:00:00Z'
----

== `inOffset(datetime: String, offset: String): String`
Returns the given `datetime` in the given timezone `offset`, changing the date and time as appropriate.

.Example
----
tro.datetime.inOffset('2020-12-31T23:19:35Z', '-08:00')
----
.Result
----
'2020-12-31T15:19:35-08:00'
----

== `compare(datetime1: String, datetime2: String): String`
Returns:

`1` if `datetime1` is after `datetime2`

`-1` if `datetime1` is before `datetime2`

`0` if `datetime1` and `datetime2` are the same

.Example
----
tro.datetime.compare('2020-12-31T23:19:35Z','2020-01-01T00:00:00Z')
----
.Result
----
1
----

== `of(parts: Object[Number|String]): String`
Returns the `String` representation of the date and time given in `parts` as an `Object` of the form:

----
{
    year: Number, month: Number, day: Number,
    hour: Number, minute: Number, second: Number,
    timezone: String
}
----

where all elements are optional.

.Example
----
local parts = {
    'year': 2021,
    'timezone': '-08:00'
};

tro.datetime.of(parts)
----
.Result
----
'2021-01-01T00:00:00-08:00'
----

== `between(datetime1: String, datetime2: String): String`
Returns the ISO-8601 duration between `datetime1` and `datetime2`.

.Example
----
local date1 = '2019-09-20T18:53:41.425Z';
local date2 = '2019-09-14T18:53:41.425Z';

tro.datetime.between(date1, date2)
----
.Result
----
'-P6D'
----

== `format(datetime: String, format: String): String`
Returns the given `datetime` formatted in the requested `format`.

.Example
----
tro.datetime.format('2019-09-20T18:53:41.425Z', 'yyyy/MM/dd')
----
.Result
----
'2019/09/20'
----

== `isLeapYear(datetime: String): String`
Returns a `true` if `datetime` is a leap year, otherwise `false`.

.Example
----
tro.datetime.isLeapYear('2019-09-14T18:53:41.425Z')
----
.Result
----
false
----

== `minus(datetime: String, duration: String): String`
Returns the result of subtracting the specified ISO-8601 `duration` from the given `datetime`.

.Example
----
tro.datetime.minus('2019-09-20T18:53:41Z', 'P2D')
----
.Result
----
'2019-09-18T18:53:41Z'
----

== `now(): String`
Returns the current datetime.

.Example
----
tro.datetime.now()
----
.Result
----
'2021-01-05T13:09:45.476375-05:00'
----

== `parse(datetime: String|Number, format: String): String`
Returns an ISO-8601 extended offset date-time from the given `datetime` using the specified `format`.

you can use `'epoch'` or `'timestamp'` as the inputFormat

.Example
----
tro.datetime.parse('12/31/1990 10:10:10', 'MM/dd/yyyy HH:mm:ss')
----
.Result
----
'1990-12-31T10:10:10Z'
----

== `plus(datetime: String, duration: String): String`
Returns the result of adding the specified ISO-8601 `duration` to the given `datetime`.

.Example
----
tro.datetime.plus('2019-09-18T18:53:41Z', 'P2D')
----
.Result
----
'2019-09-20T18:53:41Z'
----

== `toLocalDate(datetime: String): String`
Returns the given `datetime` without time or offset.

.Example
----
tro.datetime.toLocalDate('2019-07-04T18:53:41Z')
----
.Result
----
'2019-07-04'
----

== `toLocalDateTime(datetime: String): String`
Returns the given `datetime` without an offset.

.Example
----
tro.datetime.toLocalDateTime('2019-07-04T21:00:00Z')
----
.Result
----
'2019-07-04T21:00:00'
----

== `toLocalTime(datetime: String, format: String): String`
Returns the given `datetime` without date or offset.

.Example
----
tro.datetime.toLocalTime('2019-07-04T21:00:00Z')
----
.Result
----
'21:00:00'
----

== `toParts(datetime: String): Object[Number|String]`
Returns the constituent parts of the given `datetime`, as an `Object` of the form:

----
{
    year: Number, month: Number, day: Number,
    hour: Number, minute: Number, second: Number,
    offset: String
}
----

.Example
----
tro.datetime.toParts('2019-07-04T21:00:00Z')
----
.Result
----
{
    year: 2019, month: 7, day: 4,
    hour: 21, minute: 0, second: 0,
    offset: 'Z'
}
----

== `today(): String`
Returns the current day at midnight.

.Example
----
tro.datetime.today
----

.Result
----
'2021-01-05T00:00:00-05:00'
----

== `tomorrow(): String`
Returns the next day at midnight.

.Example
----
tro.datetime.tomorrow
----

.Result
----
'2021-01-06T00:00:00-05:00'
----

== `yesterday(): String`
Returns the previous day at midnight.

.Example
----
tro.datetime.yesterday
----

.Result
----
'2021-01-04T00:00:00-05:00'
----
