= `tro.math`

== `abs(num: Number): Number`
Returns the absolute value of `num`.

.Example
----
tro.math.abs(-1)
----
.Result
----
1
----

== `acos(num: Number): Number`
Returns the arc cosine of the given `num`.

.Example
----
tro.math.acos(1)
----
.Result
----
0
----

== `asin(num: Number): Number`
Returns the arc sine of the given `num`.

.Example
----
tro.math.asin(1)
----
.Result
----
1.5707963267948966
----

== `atan(num: Number): Number`
Returns the arc tangent of the given `num`.

.Example
----
tro.math.atan(1)
----
.Result
----
0.7853981633974483
----

== `avg(arr: Array[Number]): Number`
Returns the average of the numbers in `arr`.

.Example
----
tro.math.avg([1,2,3])
----
.Result
----
2
----

== `ceil(num: Number): Number`
Returns the ceiling (aka round up) of the given `num`.

.Example
----
tro.math.ceil(1.01)
----
.Result
----
2
----

== `clamp(num: Number, min: Number, max: Number): Number`
Returns `num` if it exists between `min` and `max`, otherwise the one that is closest.

.Example
----
tro.math.clamp(100, 0, 10)
----
.Result
----
10
----

== `cos(num: Number): Number`
Returns the cosine of the give `num`.

.Example
----
tro.math.cos(0)
----
.Result
----
1
----

== `exp(num: Number): Number`
Returns Euler's number e, to the power of `num`.

.Example
----
tro.math.exp(2)
----
.Result
----
7.38905609893065
----

== `exponent(num: Number): Number`
Returns the exponent portion of the double-precision binary floating-point representation (IEEE 754:binary64) of the given `num`.

.Example
----
tro.math.exponent(2)
----
.Result
----
2
----

== `floor(num: Number): Number`
Returns the floor (aka round down) of the given `num`.

.Example
----
tro.math.floor(4.99)
----
.Result
----
4
----

== `log(num: Number): Number`
Returns the natural logarithm of the given `num`.

.Example
----
tro.math.log(2)
----
.Result
----
0.6931471805599453
----

== `mantissa(num: Number): Number`
Returns the fraction portion (aka significand) of the double-precision binary floating-point representation (IEEE 754:binary64) of the given `num`.

.Example
----
tro.math.mantissa(2)
----
.Result
----
0.5
----

== `pow(num: Number1, num: Number2)`
Returns the value of `num1` raised to the power of `num2`.

.Example
----
tro.math.pow(2, 2)
----
.Result
----
4
----

== `random`
Returns a pseudo-random double-precision floating-point number between `0` and `1`.

.Example
----
tro.math.random
----
.Result
----
0.5963038027787421
----

== `randomInt(num: Number): Number`
Returns a pseudo-random integer between 0 (inclusive) and the give `num` (exclusive).

.Example
----
tro.math.randomInt(500)
----
.Result
----
485
----

== `round(num: Number): Number`
Rounds `num` to the nearest whole number.

.Example
----
tro.math.round(2.5)
----
.Result
----
3
----

== `sin(num: Number): Number`
Returns the sine of the given `num`.

.Example
----
tro.math.sin(1)
----
.Result
----
0.8414709848078965
----

== `sqrt(num: Number): Number`
Returns the square root of the given `num`.

.Example
----
tro.math.sqrt(4)
----
.Result
----
2
----

== `sum(arr: Array[Number])`
Returns the sum of all numbers in `arr`.

.Example
----
tro.math.sum([10, 20, 30])
----
.Result
----
60
----

== `tan(num: Number): Number`
Returns the tangent of the given `num`.

.Example
----
tro.math.tan(1)
----
.Result
----
1.5574077246549023
----
